language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - yarn install
  - yarn generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: fae576e550f0024690a72d23c0d13c8a14260412
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master