language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - gh-pages

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: fae576e550f0024690a72d23c0d13c8a14260412
  target-branch: master
  local-dir: dist
  on:
    branch: gh-pages